service: dynamo-error-handling-in-code
provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource:
        - ${cf:demo-database-dynamo.DynamoDBDemoArn}
    - Effect: 'Allow'
      Action:
        - 'sns:*'
      Resource:
        -  ${cf:phase-3-error-handling.SNSDynamoDLQArn}
    - Effect: 'Allow'
      Action:
        - 'kinesis:*'
      Resource:
        -  ${cf:demo-kinesis-stream.KinesisStreamDemoArn}
custom:
  retryAttempts: 3

functions:
  dynamo-processor:
    handler: lambda.handler
    events:
      - stream:
          type: dynamodb
          arn: ${cf:demo-database-dynamo.DynamoDBDemoStreamArn}
          batchSize: 1
          maximumRetryAttempts: ${self:custom.retryAttempts}
          enabled: true
    environment:
      kinesisName: ${cf:demo-kinesis-stream.KinesisStreamDemoName}
      snsArn: ${cf:phase-3-error-handling.SNSDynamoDLQArn}
      retryAttempts: ${self:custom.retryAttempts}